function [UD2] = UD2_setup(info)

%--------------------------------------------------------------------------
UD2 = PAL_AMUD_setupUD('up',1,'down',1,...
        'stepSizeDown',info.UD2_step_size_down,...
        'stepSizeUp',info.UD2_step_size_up,...
        'stopCriterion',info.UD2_stop_criterion,...
        'stopRule',info.UD2_stop_rule,...
        'startValue',info.UD2_start_value,...
        'xMax',info.UD2_xmax,...
        'xMin',info.UD2_xmin);
end